name: "GitHub Issues to Azure DevOps"
description: "This action creates an ADO work item when a GitHub issue gets a specific label"
author: "captainbrosset"
branding:
  icon: "refresh-cw"
  color: "yellow"
inputs:
  label:
    description: 'The label that needs to be applied for the issue to be synced to ADO'
    required: true
  ado_organization:
    description: 'The name of the ADO organization where the work item should be created'
    required: true
  ado_project:
    description: 'The name of the project within the ADO organization'
    required: true
  ado_tags:
    description: 'A list of tags to add to the newly created work item, separated by semi-colon (;)'
    required: false
  ado_gh_closed_tag: 
    description: 'The name of the tag to add/remove on work items to indicate whether the corresponding GitHub issue is closed. Defaults to "GitHub_Closed"'
    required: false
  parent_work_item:
    description: 'The number of a work item to use as a parent for the newly created work item'
    required: false
  ado_area_path:
    description: 'The area path under which the work item should be created'
    required: true
outputs:
  id:
    description: "id of work item created"
runs:
  using: "node12"
  main: "index.js"
